### ISSUE TITLE
M1A2 SEPv3 TC Bug

### ISSUE THREAD

**Issue by FlakBones** [61st/custom#28]
**Description:**

**Steps to reproduce:**
1. Spawn M1A2 SEPv3
2. Enter TC Seat
3. Attempt to take CROWS control or view GPSE.

**Expected behavior:**
Neither function works and the TC sight is unstabilized, unsure if the sight is supposed to be stabilized in the first place.

**Where did the issue occur?**
- 61st Main

**Log Files:**
- N/A

**Additional context:**
Spawning a vehicle through Zeus did not resolve.

**Screenshots:**
![107410_20240721192648_1](https://github.com/user-attachments/assets/386b993d-18f2-491b-87d6-f843c685ed44)

**Comment by YonVclaw** [comment]
OBE
