### ISSUE TITLE
Unable to change Pylons on new Hatchet MH-60 DAP and DAP MLASS

### ISSUE THREAD

**Issue by Wildeer** [61st/custom#39]
**Description:**
Cannot use ACE logistics with ammo truck and toolkit to change the pylons on the MH-60 DAP

**Steps to reproduce:**
1. Join 61st operations sever
2. spawn in Ammo Truck
3. spawn in MH-60 DAP
4. attempt to access the phylon menu through ace as per normal.
5. no option to open the menu will appear

**Expected behavior:**
I expect the option to "Edit Pylons" option to appear, and to be able to change the pylons.

**Where did the issue occur?**
- 61st Dedicated Operations Server

**Log Files:**
- N/A

**Additional context:**
It is possible ACE logistics was turned entirely off for the USAF logistics, but the USAF logistics only works with USAF vehicles at this time. 

**Screenshots:**
N/A

**Comment by YonVclaw** [comment]
fixed, no tool kit required only an ammo source, truck or ammo box
