### ISSUE TITLE
Request to add mods to list

### ISSUE THREAD

**Issue by YonVclaw** [61st/custom#4]
requesting approval to add the following mods to the mod list

 [Modular Shoothouse Parts ](https://steamcommunity.com/sharedfiles/filedetails/?id=2975882889)
To provide better training experience, with bullet proof walls and doors!

[Better CAS Environment (BCE)](https://steamcommunity.com/sharedfiles/filedetails/?id=2853828143)
Adds features to CTAB

[A3 Thermal Improvement](https://steamcommunity.com/sharedfiles/filedetails/?id=2041057379)
overhauls thermal vision mode

**[Metis Marker](https://steamcommunity.com/sharedfiles/filedetails/?id=1508091616)**
Needed to sync with https://maps.plan-ops.fr/

**Comment by whiteytidys** [comment]
All mods accepted and added to server
