### ISSUE TITLE
Medical Kit Missing 

### ISSUE THREAD

**Issue by NightmareL0ser** [61st/custom#53]
1-1 medic spot bag is missing

-AAT
-ACCUVACC
-Stethoscope 
-IVS
-Fast IO
-NDC
-BVM
-Chest Seals

**Comment by YonVclaw** [comment]
increased the medic bag size alot of the items were in the kit, 
did add iv's
and accuvace is to large to carry in a back pack and expect to have other med supplies, there is the portable suction device in the backpack
